# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import extension.modelutil


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', extension.modelutil.RandomFixedCharField(editable=False, max_length=16, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updation_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '卡片管理',
                'verbose_name_plural': '卡片管理',
            },
        ),
    ]
